# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: Book Library Service

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Book Library Service'  

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY_HOSTNAME: docker.io
  DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  IMAGE_NAME: book-library-service
  PORT: 5001

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
  
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"

   
    
    - name: Pull Kutomize files from the Infra repository
      uses: actions/checkout@v2
      with:
       repository: abvijaykumar/book-library-kube-infra

       
    - name: Generating Kustomize files 
      uses: imranismail/setup-kustomize@v1
      
    - run: |          
          ls -la
          mkdir generated
          cd generated
          kustomize edit set image app:$DOCKER_USERNAME/$IMAGE_NAME:$BUILD_NUMBER
          ls-la
          cat kustomization.yaml
          git config user.name "book-library-service-workflow GitHub Actions Bot"
          git config user.email "dummy@dummy.com"
          git status 
          git remote remove origin
          git commit -a -m "Set `app` image tag to"

    - name: Push kustomize file to Infra repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          with:
            source-directory: generated/
            destination-github-username: 'abvijaykumar'
            destination-repository-name: 'book-library-kube-infra'
            user-email: vijjunoreply@test.com
            commit-message: Generated Kustomize files from build $BUILD_NUMBER
            target-branch: main 
