# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: UI Book Library Service

on: 
  push:
    branches:
      - main
    paths:
      - 'bozo-book-library-ui/**'
  workflow_dispatch:
    name:
      description: 'Test scenario tags'  

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: jp-tok
  ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  REGISTRY_HOSTNAME: docker.io
  DOCKER_USERNAME: abvijaykumar
  IMAGE_NAME: bozo-book-library-ui-service
  IKS_CLUSTER: kvijay-kube-new-cluster
  
  PORT: 5001

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry

    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
        ibmcloud cr region-set "${IBM_CLOUD_REGION}"
        ibmcloud cr login

    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"

    # Build the Docker image
    - name: Build with Docker
      run: |
        cd bozo-book-library-ui
        ls -la
        docker build . -t $DOCKER_USERNAME/$IMAGE_NAME:$BUILD_NUMBER
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    # Push the image to IBM Container Registry
    - name: Push the image to ICR
      run: |
        docker push $DOCKER_USERNAME/$IMAGE_NAME:$BUILD_NUMBER

    # Deploy the Docker image to the IKS cluster
    # - name: Deploy to IKS
    #  run: |
    #    ibmcloud ks cluster config --cluster $IKS_CLUSTER
    #    kubectl config current-context
    #    kubectl config set-context --current --namespace=bozo-book-library-dev
    #    kubectl set image deployment book-library-ui-deployments book-library-ui-service=$DOCKER_USERNAME/$IMAGE_NAME:$BUILD_NUMBER 
