# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: UI Book Library Service

on: 
  push:
    branches:
      - main
    paths:
      - 'bozo-book-library-ui/**'
  workflow_dispatch:
    name:
      description: 'Test scenario tags'  

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_HOSTNAME: docker.io
  DOCKER_USERNAME: zakiraihan
  IMAGE_NAME: bozo-book-library-ui-service
  PORT: 5001

jobs:
  setup-build-publish-deploy:
    name: Development Build & Deploy Book Library ReactJS 
    runs-on: ubuntu-latest
    environment: development
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.API_TOKEN_GITHUB}}        

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"

    # Build the Docker image
    - name: Build with Docker
      run: |
        cd bozo-book-library-ui
        ls -la
        echo "Before Docker Build"
        docker images
        docker build -f Dockerfile.dev -t $IMAGE_NAME:$BUILD_NUMBER .
        echo "After Docker Build"
        docker images

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    # Push the image to Dockerhub
    - name: Push the image to Dockerhub
      run: |
        docker image tag $IMAGE_NAME:$BUILD_NUMBER docker.io/$DOCKER_USERNAME/$IMAGE_NAME:$BUILD_NUMBER
        docker image push docker.io/$DOCKER_USERNAME/$IMAGE_NAME:$BUILD_NUMBER

    - name: Invoke book-ui-service Infra GitOps pipe
      run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{secrets.API_TOKEN_GITHUB}}" \
          --request POST \
          --data '{"event_type": "update-book-ui-service-build-number", "client_payload": { "buildnumber": "'"$BUILD_NUMBER"'" }}' \
          https://api.github.com/repos/GdtZakiRaihan/book-library-kube-infra/dispatches
